"""Writes a seed file that loads a parsed syllabus tree into `topics` and `sub_topics`.

A seed file, not a migration: on a fresh database, migrations run before the
seed that creates the chapters. On an existing project (dev, prod) a new
seed file runs once when it first arrives (`supabase db push --include-seed`)
and is never re-run, so each load or correction is a new, numbered file that
is never edited afterwards (like a migration).

Chapters are matched by subject code and slug; chapters removed from the
syllabus make everything under them removed. The markdown is the source of
truth: rows that already exist (same slug) are brought up to date (name,
removed flag, expert approval, order), so a later file carries the teacher's
corrections and approvals, and running a file again changes nothing. Rows
are never deleted (questions may use them); a renamed slug is a new row, so
a renamed line keeps its slug with `{old-slug}`. The file fails if a chapter is missing or the
counts do not match, so a typo never loads half a tree.
"""

from prepvruksha_pipeline.syllabus.tree import Chapter


def _q(text: str) -> str:
    return "'" + text.replace("'", "''") + "'"


def _b(value: bool) -> str:
    return "true" if value else "false"


def seed_sql(chapters: list[Chapter], source: str) -> str:
    topics = [(ch, t, i) for ch in chapters for i, t in enumerate(ch.topics, start=1)]
    subs = [
        (ch, t, s, i)
        for ch in chapters
        for t in ch.topics
        for i, s in enumerate(t.sub_topics, start=1)
    ]
    chapter_rows = ",\n  ".join(f"({_q(ch.subject_code)}, {_q(ch.slug)})" for ch in chapters)
    topic_rows = ",\n  ".join(
        f"({_q(ch.subject_code)}, {_q(ch.slug)}, {_q(t.slug)}, {_q(t.name)}, "
        f"{_b(t.is_removed)}, {i})"
        for ch, t, i in topics
    )
    sub_rows = ",\n  ".join(
        f"({_q(ch.subject_code)}, {_q(ch.slug)}, {_q(t.slug)}, {_q(s.slug)}, {_q(s.name)}, "
        f"{_b(s.is_removed)}, {_b(ch.expert_reviewed)}, {i})"
        for ch, t, s, i in subs
    )
    loaded_rows = ",\n  ".join(
        f"({_q(ch.subject_code)}, {_q(ch.slug)}, {_q(t.slug)}, {_q(s.slug)})"
        for ch, t, s, _ in subs
    )
    reviewed = sum(1 for ch in chapters if ch.expert_reviewed)
    # Not a query run against a database: this writes a migration file from our
    # own markdown, and every value goes through _q (quotes doubled).
    return f"""-- Syllabus tree from {source}: {len(chapters)} chapters, {len(topics)} topics,
-- {len(subs)} sub-topics ({reviewed} chapters expert-reviewed).
-- Generated by `uv run prepvruksha-pipeline syllabus-sql` (services/pipeline).
-- Never edit this file after it has been pushed: seed files run once per
-- project. Corrections go in a new, higher-numbered seed file.

drop table if exists pg_temp.syllabus_chapters;
create temporary table syllabus_chapters (subject_code text, chapter_slug text);
insert into syllabus_chapters values
  {chapter_rows};

do $$
declare
  missing text;
begin
  select string_agg(sc.subject_code || '/' || sc.chapter_slug, ', ') into missing
  from syllabus_chapters sc
  where not exists (
    select 1 from public.chapters c join public.subjects s on s.id = c.subject_id
    where s.code = sc.subject_code and c.slug = sc.chapter_slug);
  if missing is not null then
    raise exception 'syllabus: chapters not in the database: %', missing;
  end if;
end;
$$;

insert into public.topics (chapter_id, slug, name_en, is_removed, sort_order)
select c.id, v.slug, v.name, v.removed or c.is_removed, v.sort
from (values
  {topic_rows}
) as v (subject_code, chapter_slug, slug, name, removed, sort)
join public.subjects s on s.code = v.subject_code
join public.chapters c on c.subject_id = s.id and c.slug = v.chapter_slug
on conflict (chapter_id, slug) do update
  set name_en = excluded.name_en, is_removed = excluded.is_removed,
      sort_order = excluded.sort_order;

insert into public.sub_topics
  (topic_id, chapter_id, slug, name_en, is_removed, expert_reviewed, sort_order)
select t.id, t.chapter_id, v.slug, v.name, v.removed or t.is_removed, v.reviewed, v.sort
from (values
  {sub_rows}
) as v (subject_code, chapter_slug, topic_slug, slug, name, removed, reviewed, sort)
join public.subjects s on s.code = v.subject_code
join public.chapters c on c.subject_id = s.id and c.slug = v.chapter_slug
join public.topics t on t.chapter_id = c.id and t.slug = v.topic_slug
on conflict (topic_id, slug) do update
  set name_en = excluded.name_en, is_removed = excluded.is_removed,
      expert_reviewed = excluded.expert_reviewed, sort_order = excluded.sort_order;

do $$
declare
  n integer;
begin
  select count(*) into n
  from public.sub_topics st
  join public.chapters c on c.id = st.chapter_id
  join public.subjects s on s.id = c.subject_id
  join syllabus_chapters sc on sc.subject_code = s.code and sc.chapter_slug = c.slug;
  if n < {len(subs)} then
    raise exception 'syllabus: expected at least {len(subs)} sub-topics, found %', n;
  end if;
end;
$$;

-- Sub-topics in these chapters that the markdown no longer lists (e.g. a
-- renamed slug): kept, because questions may use them; listed for a person.
create temporary table syllabus_loaded
  (subject_code text, chapter_slug text, topic_slug text, slug text);
insert into syllabus_loaded values
  {loaded_rows};
do $$
declare
  extra text;
begin
  select string_agg(s.code || '/' || c.slug || '/' || t.slug || '/' || st.slug, ', ') into extra
  from public.sub_topics st
  join public.topics t on t.id = st.topic_id
  join public.chapters c on c.id = st.chapter_id
  join public.subjects s on s.id = c.subject_id
  join syllabus_chapters sc on sc.subject_code = s.code and sc.chapter_slug = c.slug
  where not exists (
    select 1 from syllabus_loaded l
    where l.subject_code = s.code and l.chapter_slug = c.slug
      and l.topic_slug = t.slug and l.slug = st.slug);
  if extra is not null then
    raise notice 'syllabus: in the database but not in the markdown (kept): %', extra;
  end if;
end;
$$;
drop table syllabus_loaded;

drop table syllabus_chapters;
"""  # noqa: S608
